import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AuthProvider from "@/components/AuthProvider";
import RoleGuard from "@/components/RoleGuard";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <RoleGuard>
            <Navbar />
            <main className="flex-1">{children}</main>

            {/* Footer */}
            <div className="px-6 md:px-12 lg:px-20 py-8 bg-gray-900 text-gray-400 text-center">
              <p className="text-sm">
                © 2026 WU-InternShip Platform. ระบบบริหารจัดการสหกิจศึกษา มหาวิทยาลัยวลัยลักษณ์
              </p>
            </div>
          </RoleGuard>
        </AuthProvider>
      </body>
    </html>
  );
}